#!/bin/bash
# Quick Setup Checklist - Print this out or keep it open while setting up

echo "⚡ CODING COACH - QUICK CHECKLIST"
echo "=================================="
echo ""
echo "BEFORE YOU START:"
echo "[ ] Download LeetCode CSV from GitHub"
echo "[ ] Clone leetcode-java repository" 
echo "[ ] Note the full path to leetcode-java"
echo ""
echo "STEP 1: Read Guides (10 min)"
echo "[ ] Open: START_HERE.md"
echo "[ ] Skim: MANUAL_SETUP_INSTRUCTIONS.md"
echo ""
echo "STEP 2: Choose Your Path"
echo "[ ] Option A: Run auto_setup.ps1 (automated)"
echo "    Command: powershell -ExecutionPolicy Bypass -File auto_setup.ps1"
echo ""
echo "[ ] Option B: Follow SETUP_GUIDE.md (manual)"
echo "    Commands: Copy-paste from the guide"
echo ""
echo "STEP 3: Prepare Environment (5 min)"
echo "[ ] cd D:\College\DL\coding-coach"
echo "[ ] .\venv\Scripts\Activate.ps1"
echo "[ ] pip install -r backend\requirements.txt"
echo "[ ] pip install sentence-transformers scikit-learn"
echo ""
echo "STEP 4: Build Dataset (15 min)"
echo "[ ] cd backend\notebooks"
echo "[ ] python build_dataset.py --leetcode-csv \"PATH\" --leetcode-java-clone \"PATH\" --output-dir ..\datasets"
echo "[ ] Verify: ls ..\datasets\train.jsonl exists"
echo ""
echo "STEP 5: Train Model (10 min)"
echo "[ ] python train_classifier.py --dataset-jsonl ..\datasets\train.jsonl --epochs 50"
echo "[ ] Verify: ls ..\models\approach_classifier.pt exists"
echo ""
echo "STEP 6: Verify Setup (5 min)"
echo "[ ] cd D:\College\DL\coding-coach"
echo "[ ] python verify_setup.py"
echo "[ ] Check: All ✅ marks"
echo ""
echo "STEP 7: Start Backend (leave running)"
echo "[ ] Open new terminal"
echo "[ ] python backend\main.py"
echo "[ ] Check: http://127.0.0.1:8000 responds"
echo ""
echo "STEP 8: Test API (5 min)"
echo "[ ] Open new terminal"
echo "[ ] python test_api.py"
echo "[ ] Check: All 3 tests passed"
echo ""
echo "STEP 9: Load Extension"
echo "[ ] Open Chrome: chrome://extensions/"
echo "[ ] Enable Developer mode"
echo "[ ] Load unpacked: D:\College\DL\coding-coach\extension"
echo "[ ] Check: Extension listed and enabled"
echo ""
echo "STEP 10: Test on LeetCode"
echo "[ ] Go to: https://leetcode.com/problems/two-sum/"
echo "[ ] Paste Java code"
echo "[ ] Click ⚡ button"
echo "[ ] Check: Sidebar shows analysis"
echo ""
echo "✅ SUCCESS! Setup complete!"
echo ""
echo "=================================="
echo "Keep these terminals running:"
echo "1. Backend: python backend\main.py"
echo ""
echo "Next: Explore and improve the model!"
