### Test root
GET http://127.0.0.1:8000/

### Test embedding — simple code
POST http://127.0.0.1:8000/api/analyze
Content-Type: application/json

{
    "code": "def two_sum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        diff = target - num\n        if diff in seen:\n            return [seen[diff], i]\n        seen[num] = i\n    return []",
    "language": "python"
}
### Test approach detection
POST http://127.0.0.1:8000/api/analyze
Content-Type: application/json

{
    "code": "def binary_search(arr, target):\n    left, right = 0, len(arr)-1\n    while left <= right:\n        mid = (left+right)//2\n        if arr[mid] == target: return mid\n        elif arr[mid] < target: left = mid+1\n        else: right = mid-1\n    return -1",
    "language": "python"
}

### Full analysis with Groq
POST http://127.0.0.1:8000/api/analyze
Content-Type: application/json

{
    "code": "def two_sum(nums, target):\n    for i in range(len(nums)):\n        for j in range(i+1, len(nums)):\n            if nums[i] + nums[j] == target:\n                return [i, j]\n    return []",
    "language": "python",
    "problem_name": "Two Sum"
}

### Analyze and save to Supabase
POST http://127.0.0.1:8000/api/analyze
Content-Type: application/json

{
    "code": "def two_sum(nums, target):\n    for i in range(len(nums)):\n        for j in range(i+1, len(nums)):\n            if nums[i] + nums[j] == target:\n                return [i, j]\n    return []",
    "language": "python",
    "problem_name": "Two Sum"
}

###

### Get history
GET http://127.0.0.1:8000/api/history

### Get Interview Readiness Score
GET http://127.0.0.1:8000/api/score

### Submit Binary Search solution
POST http://127.0.0.1:8000/api/analyze
Content-Type: application/json

{
    "code": "def binary_search(arr, target):\n    left, right = 0, len(arr)-1\n    while left <= right:\n        mid = (left+right)//2\n        if arr[mid] == target: return mid\n        elif arr[mid] < target: left = mid+1\n        else: right = mid-1\n    return -1",
    "language": "python",
    "problem_name": "Binary Search"
}

###

### Submit DP solution
POST http://127.0.0.1:8000/api/analyze
Content-Type: application/json

{
    "code": "def climb_stairs(n):\n    if n <= 2:\n        return n\n    dp = [0] * (n+1)\n    dp[1] = 1\n    dp[2] = 2\n    for i in range(3, n+1):\n        dp[i] = dp[i-1] + dp[i-2]\n    return dp[n]",
    "language": "python",
    "problem_name": "Climbing Stairs"
}

GET http://127.0.0.1:8000/api/score